language: node_js
node_js:
  - "14"
  - "12"
  - "10"
cache:
  directories:
    - node_modules
if: branch = master OR branch =~ ^next- OR branch =~ ^fix-v\d+\. OR tag =~ ^v\d+\.
script:
  - yarn format:check
  - yarn build:prod
  - yarn test
after_success:
  - yarn coverage
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      env: STEP=LEGACY
      script:
        - yarn build:prod
        - nvm install 0.12
        - node test/legacy/main.js
    - stage: test
      env: STEP=COMMONJS_ESM
      script:
        - PROJECT_ROOT_PATH="$(pwd)"
        - yarn build:prod
        - yarn link
        # Node 8 does not understand ES modules
        - nvm install 8
        - cd ${PROJECT_ROOT_PATH}
        - cd test/esm
        - node --version
        - sh run.sh
        # Node 12 requires a flag to support ES modules but can understand them
        - nvm install 12
        - cd ${PROJECT_ROOT_PATH}
        - cd test/esm
        - node --version
        - sh run.sh
        # Node >=13.2.0 enables support for ES modules by default
        - nvm install 13
        - cd ${PROJECT_ROOT_PATH}
        - cd test/esm
        - node --version
        - sh run.sh
    - stage: deploy
      if: tag =~ ^v\d+\.
      script:
        - yarn build:prod
      deploy:
        provider: npm
        email: npm@dubien.org
        skip_cleanup: true
        api_key:
          secure: jgmcqj5jMrAn31dTzI2eJ9ya99mDXF6cESsQF0vDsUx98z6flHsMAGtnE7uJC/PSlYKHDcX5aNXkJLpZUeqDch6zMh4qzQYNuasK+EPD5zJGy3dVz5JrF6Jidk/WbWtR3S6zm8+WFou+9oaniei4hXucq5qVo89kRPAfGPsyJJNRwKOLVakHZGkVJ2s/rgMeP4UlFWN0QxfHYHAEmkdWvW2CMQwTLuValrax17xvQFIZRYbEAGCrFIM1u4kO0hTxKwwy+HjamOklRwqHyMHYr5JvRsqzaFFIp05ff6LLBlGSJNM19tEjPLBkhzj5GFyhM83vAQpPz/pzSrUSNMfkLQPre6yV9H4gLIyJhCZvs3Isl/8Fm1K+XX7DlpiwDPLtDM7JRPFmZjPYIJRLIuANhDThsGNsP8Dw170aMMXforUMzNHC9Iv/nkuLzPsB2iAhW+cbWjGiW+/Sn6JJn+bavMLK1gnZsH+ShkHWbm9vvDLCDJXw4RTsocVZxi22ZDsRkc+q9oV+iSJYIoD4p9lppEH2BNE96sqm+MiO1JWj9j4GRoBmv0x0q2Tw9Wgfw4Oy2LmToSV+APuWJB+5IqZ7M3Iav8cr6nDp2Eo7Y1rqIkz2L2Hqi6hj8FpZFFEChP6J4rdQFp/XJl7X+XxE3/t8sdod2stK/0EvO5SPWsIcB+Q=
        on:
          tags: true
      repo: dubzzz/pure-rand
