language: node_js
node_js:
- '6'
- '7'
- '8'
- '10'
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run build:esm
- npm run test
- npm run webbuild
after_success:
- npm run coverage
deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: Pw21byBCQrPrsDZSITSgo2BTiEzTpeUEYO3P/7BwaVJBV81B9jn6fxA4tX6RwxB/04OwetlRgdcZeZwvFZ1Dwq8dIElOGedkB3vO9O5Qxcp/WONOTkeuzjCOGCv9u52zbYsfXSspV3K9Z/58+3vJLizWuLWAdZscxr46HXLaCSg0KFQtlLrLIC4lo8uulxjFAv/92nkWXnu/+RB35FAz1K7FGdtFhBe/P3rmYXrJd9JzBc+dA5TRa2PdgxrI982JXTy2anwhhQ73h6gopNEDbd/+bUmpOQEyTAfeIva2zhaegcAUYpMVo27XxHjj29QAj7ycX+8dmHFwna6nZS03Q2Ekq82JqBXAsjHBEOsKA4tZLlUKyPEIVaYOb+SMQw1M8BCeAq/FJMQf0mFUDRnxFO1pSglIgBQO7NkfcaxCSDvbE4c1sYWrpJGrd91m8TXRBro0Hzn4qLtI9awRKK5oozXhWWJRRQP77VTrdDM2IEZ06sGD27rWPdcCDW/o8zF75yPaN731hHwZ3JmQ39r2XOdxdvcwxJcaTKzTBFABaZU8g50EA91QmEYYz3TrVy1FTiaOf+g35+pLQNupY9giZBuXMPLJVgqpR3CZg/Wga4T1AS03ro5svJRwmaL/YSazmz/xP6WintxZZVBqpM5V3MyB6ooZEAWk0mVKky8fkJo=
  on:
    tags: true
    repo: dubzzz/pure-rand
