language: node_js
node_js:
  - '6'
  - '7'
  - '8'

cache:
  directories:
  - node_modules

script:
  - npm run build
  - npm run test

after_success:
  - npm run coverage
  - npm run codeclimate
