[package]
name = "pure-rand-rs"
version = "0.0.0"
authors = ["Nicolas DUBIEN <github@dubien.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[profile.release]
opt-level = 3
