import type { JumpableRandomGenerator } from '../types/JumpableRandomGenerator';

// XoroShiro128+ with a=24, b=16, c=37,
// - https://en.wikipedia.org/wiki/Xoroshiro128%2B
// - http://prng.di.unimi.it/xoroshiro128plus.c
class XoroShiro128Plus implements JumpableRandomGenerator {
  constructor(
    private s01: number,
    private s00: number,
    private s11: number,
    private s10: number,
  ) {}
  clone(): XoroShiro128Plus {
    return new XoroShiro128Plus(this.s01, this.s00, this.s11, this.s10);
  }
  next(): number {
    const out = (this.s00 + this.s10) | 0;
    // a = s0[n] ^ s1[n]
    const a0 = this.s10 ^ this.s00;
    const a1 = this.s11 ^ this.s01;
    const s00 = this.s00;
    const s01 = this.s01;
    // s0[n+1] = rotl(s0[n], 24) ^ a ^ (a << 16)
    this.s00 = (s00 << 24) ^ (s01 >>> 8) ^ a0 ^ (a0 << 16);
    this.s01 = (s01 << 24) ^ (s00 >>> 8) ^ a1 ^ ((a1 << 16) | (a0 >>> 16));
    // s1[n+1] = rotl(a, 37)
    this.s10 = (a1 << 5) ^ (a0 >>> 27);
    this.s11 = (a0 << 5) ^ (a1 >>> 27);
    return out;
  }
  jump(): void {
    // equivalent to 2^64 calls to next()
    // can be used to generate 2^64 non-overlapping subsequences
    let ns01 = 0;
    let ns00 = 0;
    let ns11 = 0;
    let ns10 = 0;
    const jump = [0xd8f554a5, 0xdf900294, 0x4b3201fc, 0x170865df];
    for (let i = 0; i !== 4; ++i) {
      for (let mask = 1; mask; mask <<= 1) {
        // Because: (1 << 31) << 1 === 0
        if (jump[i] & mask) {
          ns01 ^= this.s01;
          ns00 ^= this.s00;
          ns11 ^= this.s11;
          ns10 ^= this.s10;
        }
        this.next();
      }
    }
    this.s01 = ns01;
    this.s00 = ns00;
    this.s11 = ns11;
    this.s10 = ns10;
  }
  getState(): readonly number[] {
    return [this.s01, this.s00, this.s11, this.s10];
  }
}

export function xoroshiro128plusFromState(state: readonly number[]): JumpableRandomGenerator {
  const valid = state.length === 4;
  if (!valid) {
    throw new Error('The state must have been produced by a xoroshiro128plus RandomGenerator');
  }
  return new XoroShiro128Plus(state[0], state[1], state[2], state[3]);
}

export function xoroshiro128plus(seed: number): JumpableRandomGenerator {
  return new XoroShiro128Plus(-1, ~seed, seed | 0, 0);
}

/**
 * Advance a SplitMix32 counter and return the hashed output.
 * SplitMix32 is a fast, high-quality 32-bit counter-based PRNG designed by
 * Steele, Lea & Flood (2014). It is the canonical seeder recommended by
 * Sebastiano Vigna for initialising xoshiro/xoroshiro generators from a
 * single or accumulated integer value.
 */
function splitMix32(state: number): { next: number; value: number } {
  const next = (state + 0x9e3779b9) | 0;
  let z = next;
  z = Math.imul(z ^ (z >>> 16), 0x85ebca6b) | 0;
  z = Math.imul(z ^ (z >>> 13), 0xc2b2ae35) | 0;
  return { next, value: z ^ (z >>> 16) };
}

/**
 * Seed an XoroShiro128+ generator using an array of 32-bit integers.
 *
 * Motivation: the single-integer constructor `xoroshiro128plus(seed)` can only
 * produce 2^32 distinct starting states out of the 2^128 the algorithm supports.
 * Seeding from an array lets callers supply richer entropy (e.g. multiple
 * independently obtained random values, or the bytes of a UUID/hash).
 *
 * The implementation follows the approach recommended by Sebastiano Vigna
 * (the algorithm author) in the xoshiro reference code: use SplitMix64 to
 * fill the state. Here we use the 32-bit analogue SplitMix32 because pure-rand
 * operates entirely in 32-bit arithmetic. Each seed element is folded into a
 * running SplitMix32 counter, and the four 32-bit state words are then
 * generated by four successive SplitMix32 steps, ensuring at least one
 * non-zero word even when all seeds are zero.
 *
 * @param seeds - An array of 32-bit integer seeds (treated as signed 32-bit
 *   values). An empty array is valid and produces a deterministic state.
 */
export function xoroshiro128plusByArray(seeds: readonly number[]): JumpableRandomGenerator {
  // Fold all seed elements into a single 32-bit accumulator using SplitMix32 mixing.
  let acc = 0;
  for (let i = 0; i < seeds.length; i++) {
    acc = splitMix32((acc + (seeds[i] | 0)) | 0).next;
  }

  // Expand the accumulator into 4 independent state words via SplitMix32.
  const r0 = splitMix32(acc);
  const r1 = splitMix32(r0.next);
  const r2 = splitMix32(r1.next);
  const r3 = splitMix32(r2.next);

  // XoroShiro128+ requires a non-all-zero state.  SplitMix32 guarantees that
  // the output sequence visits all 2^32 values before repeating, so at least
  // one of the four words is non-zero (they are all zero only if every
  // SplitMix32 output happened to be zero, which cannot occur in a full-period run).
  return new XoroShiro128Plus(r0.value, r1.value, r2.value, r3.value);
}
